CREATE DATABASE `Jolie`;

USE `Jolie`;
Drop database `Jolie`;

INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES ('Quyền','ROLE','Admin','ADMIN');
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`) VALUES('Quyền','ROLE','Khách Hàng','USER');
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Giới tính','SEX','Nam',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Giới tính','SEX','Nữ',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Loại tài khoản','TYPE','Jolie',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Trạng thái sản phẩm','PRODUCT_STATUS','Còn bán',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Trạng thái sản phẩm','PRODUCT_STATUS','Ngưng bán',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Phương thức thanh toán','PAYMENTMETHOD','Tiền mặt','tien-mat');
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Phương thức thanh toán','PAYMENTMETHOD','E-Banking','e-banking');
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Phương thức vận chuyển','SHIPPINGMETHOD','Hỏa tốc','hoa-toc');
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Phương thức vận chuyển','SHIPPINGMETHOD','48h','48h');
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Danh mục mỹ phẩm','CATEGORY','Mỹ phẩm High-end','my-pham-high-end');
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Danh mục mỹ phẩm','CATEGORY','Chăm sóc da mặt','cham-soc-da-mat');
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Danh mục mỹ phẩm','CATEGORY','Trang điểm','trang-diem');
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Danh mục mỹ phẩm','CATEGORY','Chăm sóc tóc và Da đầu','cham-soc-toc-va-da-dau');
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Danh mục mỹ phẩm','CATEGORY','Chăm sóc cơ thể','cham-soc-co-the');
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Danh mục mỹ phẩm','CATEGORY','Chăm sóc cá nhân','cham-soc-ca-nhan');
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Danh mục mỹ phẩm','CATEGORY','Nước hoa','nuoc-hoa');
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Trạng thái đơn hàng','BILL_STATUS','Mới đặt',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Trạng thái đơn hàng','BILL_STATUS','Đang xử lý',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Trạng thái đơn hàng','BILL_STATUS','Thành công',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Trạng thái đơn hàng','BILL_STATUS','Đã hủy',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','BIODERMA',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','LA ROCHE-POSAY',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','SUNPLAY',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','SHU UEMURA',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','LANCÔME',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','HAIRBURST',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','TSUBAKI',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','VASELINE',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','HATOMUGI',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','LANEIGE',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','LOREAL',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','EVOLUDERM',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','COCOON',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','50 Megumi',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','REMOS',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','MAC',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','3CE',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','Some By Mi',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','Reen',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','Tesori dOriente',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','Paulas Choice',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','PS',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','LAURA ANNE',NULL);
INSERT INTO `config` ( `code`, `groupcode` ,`name`, `value`)VALUES('Thương hiệu sản phẩm','BRAND','Calvin Klein',NULL);
-------------------------------------------

INSERT INTO `media`  (`file_name`)VALUES ('http://res.cloudinary.com/dt3xylr2x/image/upload/v1685334080/f1503bc7-5d4b-435b-bfbe-1d6310dfd429.jpg');
INSERT INTO `media`  (`file_name`)VALUES('http://res.cloudinary.com/dt3xylr2x/image/upload/v1685334676/56a15791-df08-46c3-9321-ed539e570e15.jpg');
INSERT INTO `media`  (`file_name`)VALUES('http://res.cloudinary.com/dt3xylr2x/image/upload/v1685334792/46f35cac-3af4-40a5-b2d5-9fde8e95e3d1.jpg');
INSERT INTO `media`  (`file_name`)VALUES('http://res.cloudinary.com/dt3xylr2x/image/upload/v1685334936/257056fc-c42d-4678-b5fb-33992841a9e2.jpg');
INSERT INTO `media`  (`file_name`)VALUES('http://res.cloudinary.com/dt3xylr2x/image/upload/v1685335040/5b950a8f-c1c3-49ab-a047-7f3d7aa8f7a4.jpg');
INSERT INTO `media`  (`file_name`)VALUES('http://res.cloudinary.com/dt3xylr2x/image/upload/v1685335166/58b35f56-42af-438b-85ec-f2cd9e86719a.jpg');
INSERT INTO `media`  (`file_name`)VALUES('http://res.cloudinary.com/dt3xylr2x/image/upload/v1685335307/2dd76375-17d6-4f41-9f7f-beb015cfc31b.jpg');
INSERT INTO `media`  (`file_name`)VALUES('http://res.cloudinary.com/dt3xylr2x/image/upload/v1685335424/cabdba74-85a8-429e-8197-2decee0039ba.jpg');
INSERT INTO `media`  (`file_name`)VALUES('http://res.cloudinary.com/dt3xylr2x/image/upload/v1685335554/139b5b92-d2b7-4abe-af21-24419ea9a144.jpg');
INSERT INTO `media`  (`file_name`)VALUES('http://res.cloudinary.com/dt3xylr2x/image/upload/v1685335650/958bdd1c-7f91-4dde-bcaf-4bc448c42ebd.jpg');
INSERT INTO `media`  (`file_name`)VALUES('http://res.cloudinary.com/dt3xylr2x/image/upload/v1685335843/02d8732e-6a46-46cf-898a-5e48013085b2.jpg');
INSERT INTO `media`  (`file_name`)VALUES('http://res.cloudinary.com/dt3xylr2x/image/upload/v1685336095/b9843056-d9e5-4e32-9f17-e04371f3dad9.png');
INSERT INTO `media`  (`file_name`)VALUES('http://res.cloudinary.com/dt3xylr2x/image/upload/v1685336417/c0ef71c1-ba73-48ed-9ca9-52f8375e937b.png');
INSERT INTO `media`  (`file_name`)VALUES('http://res.cloudinary.com/dt3xylr2x/image/upload/v1685336641/54bbb52d-4960-448e-a680-cf2b53b074f9.jpg');
INSERT INTO `media`  (`file_name`)VALUES('http://res.cloudinary.com/dt3xylr2x/image/upload/v1685336790/78412082-0c36-4faf-ad8a-e5ae4557a671.jpg');
INSERT INTO `media`  (`file_name`)VALUES('http://res.cloudinary.com/dt3xylr2x/image/upload/v1685336989/ff3e2b7b-e7e5-45a7-936a-f2bf633f6b92.jpg');
INSERT INTO `media`  (`file_name`)VALUES('http://res.cloudinary.com/dt3xylr2x/image/upload/v1685337225/c988ccfe-7c36-4258-9c33-accde85431f9.jpg');
--------------------------------------------------
INSERT INTO `product`(`description`,`inventory`,`name`,`origin`, `price`,  `price_sale`,`brand`, `category`,`image` ) VALUES('Berry - Hương Quả Mọng (sản phẩm chính của dòng mặt na ngủ dành cho môi): chứa hương thơm của các loại quả mọng sảng khoái và ngọt ngào.',100,'Mặt Nạ Ngủ Môi Laneige','Nhật Bản',179000,NULL,32,12,1);
INSERT INTO `product`(`description`,`inventory`,`name`,`origin`, `price`,  `price_sale`,`brand`, `category`,`image` )  VALUES('Dầu Tẩy Trang & Làm Sạch Ultime8. Nuôi Dưỡng Làn Da với công thức tích hợp 8 loại dầu quý hiếm, không chỉ có tác dụng nhẹ nhàng lấy đi lớp trang điểm, bụi bẩn trên da mà còn có chức năng chăm sóc làn da, mang lại một cảm giác mềm mại như tơ lụa, mịn màng khi chạm vào làn da.',100,'Dầu Tẩy Trang Shu Uemura ','Nhật Bản',950000,NULL,26,12,2);
INSERT INTO `product`(`description`,`inventory`,`name`,`origin`, `price`,  `price_sale`,`brand`, `category`,`image` ) VALUES('Công nghệ micellar sử dụng các hạt micelles thần kì tương thích hoàn hảo với lớp lipid tự nhiên của da. Yếu tố cấu thành nên hạt micelle là các ester acid béo, tương tự như cấu trúc lớp phospholipid của màng tế bào da, giúp tái tạo lớp màng hydrolipid của da một cách tự nhiên.',100,'Nước Tẩy Trang Bioderma','Pháp',350000,NULL,23,13,3);
INSERT INTO `product`(`description`,`inventory`,`name`,`origin`, `price`,  `price_sale`,`brand`, `category`,`image` )  VALUES('Gel Rửa Mặt La Roche-Posay Effaclar Purifying Foaming Gel For Oily Sensitive Skin Dành Cho Da Dầu, Nhạy Cảm hiện đã có mặt tại Hasaki với 3 dung tích đa dạng phù hợp với từng nhu cầu riêng biệt',50,'Rửa Mặt La RochePosay','Pháp',276000,NULL,24,13,4);
INSERT INTO `product`(`description`,`inventory`,`name`,`origin`, `price`,  `price_sale`,`brand`, `category`,`image` ) VALUES('Công thức đặc biệt của M.A.C giúp son lên màu cực kì chuẩn & sắc nét chỉ sau một đường lướt nhẹ trên môi. Đồng thời, son có độ giữ màu, bám màu trên môi rất tốt lên đến 5-6 tiếng sau khi sử dụng, giúp bạn luôn tự tin với đôi môi tươi tắn suốt nhiều giờ liền mà không cần phải mất thời gian thoa lại son',100,'Son Thỏi MAC ','Mỹ',650000,NULL,40,14,5);
INSERT INTO `product`(`description`,`inventory`,`name`,`origin`, `price`,  `price_sale`,`brand`, `category`,`image` ) VALUES('3CE Soft Matte Lipstick – Version Deep Under More Deep vẫn giữ nguyên kết cấu mềm mại đặc trưng và độ bám màu cao, giúp đôi môi luôn mềm mại, mịn màng như nhung. Công thức với bột đàn hồi silicon giúp son nhẹ nhàng lướt êm trên môi, cho lớp nền môi nhẹ thoáng, mịn lì, cảm giác như không đánh son. Bên cạnh đó, hạt phức hợp semi-solid sẽ giúp màu son được lưu giữ trên môi lâu hơn, không bị phai hay nứt nẻ.',100,'Son Thỏi 3CE Vỏ Trong Suốt Unstained Red ','Hàn Quốc',304000,NULL,41,14,6);
INSERT INTO `product`(`description`,`inventory`,`name`,`origin`, `price`,  `price_sale`,`brand`, `category`,`image` ) VALUES('Chai Xịt 3CE Cố Định Lớp Trang Điểm 100ml là sản phẩm xịt khoá trang điểm đến từ thương hiệu trang điểm 3CE của Hàn Quốc, bên cạnh công dụng dưỡng ẩm, làm dịu da sản phẩm còn giúp giữ lớp nền bền vững, ngăn mồ hồi, dầu thừa đem lại làn da căng bóng tự nhiên và khoẻ mạnh. Đặc biệt sản phẩm có nhũ trắng nhẹ nhàng tạo lớp nền bắt sáng và lấp lánh',100,'Xịt Khoá Nền 3CE','Hàn Quốc',289000,NULL,41,14,7);
INSERT INTO `product`(`description`,`inventory`,`name`,`origin`, `price`,  `price_sale`,`brand`, `category`,`image` )  VALUES('Mặt Nạ Đất Sét Some By Mi Super Matcha Pore Clean Clay Mask là sản phẩm mặt nạ rửa mới ra mắt thuộc dòng Super Matcha, được SOME BY MI thiết kế chuyên biệt cho tình trạng da dầu, thô ráp & lỗ chân lông to',100,'Mặt Nạ Đất Sét Some By Mi','Hàn Quốc',263000,NULL,42,13,8);
INSERT INTO `product`(`description`,`inventory`,`name`,`origin`, `price`,  `price_sale`,`brand`, `category`,`image` )  VALUES('Bộ Đôi Gội Xả Tsubaki Sạch Dầu Mát Lạnh (490ml/chai) là bộ gội xả đến từ thương hiệu chăm sóc tóc Tsubaki của Nhật Bản, với thành phần Palimitic Acid Octyl có công dụng loại bỏ dầu nhờn dư thừa trên da đầu, mang lại mái tóc bồng bềnh, suôn mượt',100,'Bộ Gội Xả Tsubaki Sạch Dầu Mát Lạnh ','Nhật Bản',264000,NULL,29,15,9);
INSERT INTO `product`(`description`,`inventory`,`name`,`origin`, `price`,  `price_sale`,`brand`, `category`,`image` )  VALUES('Với công thức dịu nhẹ không chứa sulfate, Combo Gội Xả Bưởi đến từ thương hiệu mỹ phẩm thuần chay Cocoon Việt Nam giúp làm sạch tóc, giảm gãy rụng, mang lại mái tóc đen dày, chắc khoẻ và mượt mà.',100,'Bộ Gội Xả Bưởi Cocoon','Việt Nam',347000,NULL,36,15,10);
INSERT INTO `product`(`description`,`inventory`,`name`,`origin`, `price`,  `price_sale`,`brand`, `category`,`image` )  VALUES('Kem Nhuộm Tóc Phủ Bạc Thảo Mộc Chuyên Nghiệp Reen Heukmobichaek Oriental Hair Dye Cream là dòng sản phẩm thuốc nhuộm tóc tại nhà đến từ thương hiệu Reen của Hàn Quốc. ',100,'Kem Nhuộm Tóc Reen','Hàn Quốc',109000,NULL,43,12,11);
INSERT INTO `product`(`description`,`inventory`,`name`,`origin`, `price`,  `price_sale`,`brand`, `category`,`image` )  VALUES('Sữa Tắm Nước Hoa Tesori dOriente Hương Hoa Sen lấy cảm hứng từ Nghi thức của các vị thần Phương Đông, sữa tắm nước hoa với khả năng chống oxy hóa, trẻ hóa và nuôi dưỡng làn da mềm mại, sáng khỏe nhờ các thành phần quý: Hoa Sen và Bơ hạt mỡ. Sản phẩm mang lại một cảm giác dễ chịu, sảng khoái cho tất cả các giác quan sau khi tắm với hương thơm ngọt ngào, ấm áp. ',100,'Sữa Tắm Nước Hoa Tesori dOriente','Ý',219000,NULL,44,16,12);
INSERT INTO `product`(`description`,`inventory`,`name`,`origin`, `price`,  `price_sale`,`brand`, `category`,`image` )  VALUES('Paulas Choice Weightless Body Treatment With 2 BHA là sản phẩm kem dưỡng thể tẩy tế bào chết toàn thân đến từ thương hiệu dược mỹ phẩm Paulas Choice. Công thức chứa nồng độ  Salicylic Acid (BHA) có khả năng cải thiện các vấn đề về mụn, viêm lỗ chân lông, mẩn đỏ các vùng da trên cơ thể, mang đến cho bạn làn da sạch thoáng mịn màng hơn.',100,'Kem Dưỡng Thể Paulas Choice','Mỹ',297000,NULL,45,16,13);
INSERT INTO `product`(`description`,`inventory`,`name`,`origin`, `price`,  `price_sale`,`brand`, `category`,`image` ) VALUES('Bàn Chải Điện PS S100 Pro Công Nghệ Sóng Âm là sản phẩm bàn chải điện đến từ thương hiệu chăm sóc răng miệng Ps thuộc tập đoàn Unilever của Mỹ, sử dụng công nghệ sóng âm Sonic giúp loại sạch mảng bám gấp 10 lần bàn chải thông thường',100,'Bàn Chải Điện PS ','Mỹ',850000,NULL,44,17,14);
INSERT INTO `product`(`description`,`inventory`,`name`,`origin`, `price`,  `price_sale`,`brand`, `category`,`image` )  VALUES('Picaridin: có công dụng xua đuổi côn trùng như muỗi, bọ vẹ bảo vệ cơ thể an toàn ở mọi môi trường.',1000,'Combo Xịt Chống Muỗi Remos ','Nhật Bản',90000,NULL,39,17,15);
INSERT INTO `product`(`description`,`inventory`,`name`,`origin`, `price`,  `price_sale`,`brand`, `category`,`image` )  VALUES('Nước Hoa Laura Anne Diamond Cho Nam 45ml là sản phẩm nước hoa eau de parfum cho nam đến từ thương hiệu Laura Anne được sản xuất trực tiếp tại Việt Nam với nguồn nguyên liệu nhập khẩu theo công nghệ Singapore.',100,'Nước Hoa Nam Laura Anne ','Singapo',329000,NULL,45,18,16);
INSERT INTO `product`(`description`,`inventory`,`name`,`origin`, `price`,  `price_sale`,`brand`, `category`,`image` )  VALUES('Nước Hoa Nam Nữ Calvin Klein Everyone EDT là sản phẩm nước hoa có nồng độ eau de toilette cho nam và nữ đến từ thương hiệu Calvin Klein của Mỹ. Đây là nước hoa sạch đầu tiên của Calvin Klein',100,'Nước Hoa Nam Nữ Calvin Klein ','Mỹ',10350000,NULL,46,18,17);
