package com.g10.JolieWeb.Entity;
// default package
// Generated Dec 2, 2022, 3:53:02 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "jolie")
public class Account implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String username;
	private Config configByType;
	private Config configByRole;
	private String password;
	private Date date01;
	private Date date02;
	private Accountinfo accountinfo;

	public Account() {
	}

	public Account(String username, Config configByType, Config configByRole) {
		this.username = username;
		this.configByType = configByType;
		this.configByRole = configByRole;
	}

	public Account(String username, Config configByType, Config configByRole, String password, Date date01, Date date02,
			Accountinfo accountinfo) {
		this.username = username;
		this.configByType = configByType;
		this.configByRole = configByRole;
		this.password = password;
		this.date01 = date01;
		this.date02 = date02;
		this.accountinfo = accountinfo;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "type", nullable = false)
	public Config getConfigByType() {
		return this.configByType;
	}

	public void setConfigByType(Config configByType) {
		this.configByType = configByType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "role", nullable = false)
	public Config getConfigByRole() {
		return this.configByRole;
	}

	public void setConfigByRole(Config configByRole) {
		this.configByRole = configByRole;
	}

	@Column(name = "password", length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date01", length = 19)
	public Date getDate01() {
		return this.date01;
	}

	public void setDate01(Date date01) {
		this.date01 = date01;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date02", length = 19)
	public Date getDate02() {
		return this.date02;
	}

	public void setDate02(Date date02) {
		this.date02 = date02;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "account")
	public Accountinfo getAccountinfo() {
		return this.accountinfo;
	}

	public void setAccountinfo(Accountinfo accountinfo) {
this.accountinfo = accountinfo;
	}

}