package com.g10.JolieWeb.Entity;
// default package
// Generated Dec 2, 2022, 3:53:02 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.g10.JolieWeb.DTO.BillinfoDTO;

/**
 * Billinfo generated by hbm2java
 */
@Entity
@Table(name = "billinfo", catalog = "jolie")
public class Billinfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Cart cart;
	private Config configByPaymentMethod;
	private Config configByShippingMethod;
	private float totalPrice;
	private String shippingAddress;
	private String recipientName;
	private String recipientPhone;
	private Date datePayment;
	private Config configByStatus;

	public Billinfo() {
	}

	public Billinfo(Cart cart, Config configByPaymentMethod, Config configByShippingMethod, float totalPrice,
			String shippingAddress, String recipientName, String recipientPhone, Config configByStatus) {
		this.cart = cart;
		this.configByPaymentMethod = configByPaymentMethod;
		this.configByShippingMethod = configByShippingMethod;
		this.totalPrice = totalPrice;
		this.shippingAddress = shippingAddress;
		this.recipientName = recipientName;
		this.recipientPhone = recipientPhone;
		this.configByStatus = configByStatus;
	}

	public Billinfo(Cart cart, Config configByPaymentMethod, Config configByShippingMethod, float totalPrice,
			String shippingAddress, String recipientName, String recipientPhone, Date datePayment, Config configByStatus) {
		this.cart = cart;
		this.configByPaymentMethod = configByPaymentMethod;
		this.configByShippingMethod = configByShippingMethod;
		this.totalPrice = totalPrice;
		this.shippingAddress = shippingAddress;
		this.recipientName = recipientName;
		this.recipientPhone = recipientPhone;
		this.datePayment = datePayment;
		this.configByStatus = configByStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToOne (fetch = FetchType.EAGER)
	@JoinColumn(name = "idCart", nullable = false)
	public Cart getCart() {
		return this.cart;
	}

	public void setCart(Cart cart) {
		this.cart = cart;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "paymentMethod", nullable = false)
	public Config getConfigByPaymentMethod() {
		return this.configByPaymentMethod;
	}

	public void setConfigByPaymentMethod(Config configByPaymentMethod) {
		this.configByPaymentMethod = configByPaymentMethod;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "shippingMethod", nullable = false)
	public Config getConfigByShippingMethod() {
		return this.configByShippingMethod;
	}

	public void setConfigByShippingMethod(Config configByShippingMethod) {
		this.configByShippingMethod = configByShippingMethod;
	}

	@Column(name = "totalPrice", nullable = false, precision = 12, scale = 0)
	public float getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(float totalPrice) {
		this.totalPrice = totalPrice;
	}

	@Column(name = "shippingAddress", nullable = false, length = 200)
	public String getShippingAddress() {
		return this.shippingAddress;
	}

	public void setShippingAddress(String shippingAddress) {
		this.shippingAddress = shippingAddress;
	}

	@Column(name = "recipientName", nullable = false, length = 200)
	public String getRecipientName() {
		return this.recipientName;
	}

	public void setRecipientName(String recipientName) {
		this.recipientName = recipientName;
	}

	@Column(name = "recipientPhone", nullable = false, length = 200)
	public String getRecipientPhone() {
		return this.recipientPhone;
	}

	public void setRecipientPhone(String recipientPhone) {
		this.recipientPhone = recipientPhone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datePayment", length = 19)
	public Date getDatePayment() {
		return this.datePayment;
	}

	public void setDatePayment(Date datePayment) {
		this.datePayment = datePayment;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "status", nullable = false)
	public Config getConfigByStatus() {
		return this.configByStatus;
	}

	public void setConfigByStatus(Config configByStatus) {
		this.configByStatus = configByStatus;
	}
	
	public static Billinfo fromDTO(BillinfoDTO billinfoDTO) {
        Billinfo billinfo = new Billinfo();

        billinfo.setId(billinfoDTO.getId());
        billinfo.setCart(billinfoDTO.getCart());
        billinfo.setConfigByPaymentMethod(billinfoDTO.getConfigByPaymentMethod());
        billinfo.setConfigByShippingMethod(billinfoDTO.getConfigByShippingMethod());
        billinfo.setTotalPrice(billinfoDTO.getTotalPrice());
        billinfo.setShippingAddress(billinfoDTO.getShippingAddress());
        billinfo.setRecipientName(billinfoDTO.getRecipientName());
        billinfo.setRecipientPhone(billinfoDTO.getRecipientPhone());
        billinfo.setDatePayment(billinfoDTO.getDatePayment());
        billinfo.setConfigByStatus(billinfoDTO.getConfigByStatus());

        return billinfo;
    }

}
