package com.g10.JolieWeb.Entity;
// default package
// Generated Dec 2, 2022, 3:53:02 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart", catalog = "jolie")
public class Cart implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Accountinfo accountinfo;
	private float totalPrice;
	private Integer status;
	private Set<Detailcart> detailcarts = new HashSet<Detailcart>(0);
	private Billinfo billinfo;

	public Cart() {
	}

	public Cart(Accountinfo accountinfo) {
		this.accountinfo = accountinfo;
		this.totalPrice = 0;
		this.status = 0;
	}

	public Cart(Accountinfo accountinfo, float totalPrice, Integer status, Set<Detailcart> detailcarts,
			Billinfo billinfo) {
		this.accountinfo = accountinfo;
		this.totalPrice = totalPrice;
		this.status = status;
		this.detailcarts = detailcarts;
		this.billinfo = billinfo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idUser", nullable = false)
	public Accountinfo getAccountinfo() {
		return this.accountinfo;
	}

	public void setAccountinfo(Accountinfo accountinfo) {
		this.accountinfo = accountinfo;
	}

	@Column(name = "totalPrice", nullable = false, precision = 12, scale = 0)
	public float getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(float totalPrice) {
		this.totalPrice = totalPrice;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "cart")
	public Set<Detailcart> getDetailcarts() {
		return this.detailcarts;
	}

	public void setDetailcarts(Set<Detailcart> detailcarts) {
		this.detailcarts = detailcarts;
	}

	@OneToOne(fetch = FetchType.EAGER, mappedBy = "cart")
	public Billinfo getBillinfo() {
		return this.billinfo;
	}

	public void setBillinfo(Billinfo billinfo) {
		this.billinfo = billinfo;
	}

}
