package com.g10.JolieWeb.Entity;
// default package
// Generated Dec 2, 2022, 3:53:02 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Media generated by hbm2java
 */
@Entity
@Table(name = "media", catalog = "jolie")
public class Media implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String title;
	private String description;
	private String fileName;
	private String fileType;
	private String fileExtension;
	private String mimeType;
	private Integer fileSize;
	private String folder;
	private String fileBatch;
	private Integer iduser01;
	private Date date01;
	private Set<Product> products = new HashSet<Product>(0);

	public Media() {
	}

	public Media(String title, String description, String fileName, String fileType, String fileExtension,
			String mimeType, Integer fileSize, String folder, String fileBatch, Integer iduser01, Date date01,
			Set<Product> products) {
		this.title = title;
		this.description = description;
		this.fileName = fileName;
		this.fileType = fileType;
		this.fileExtension = fileExtension;
		this.mimeType = mimeType;
		this.fileSize = fileSize;
		this.folder = folder;
		this.fileBatch = fileBatch;
		this.iduser01 = iduser01;
		this.date01 = date01;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", length = 1000)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "fileName", length = 1000)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "fileType", length = 1000)
	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	@Column(name = "fileExtension", length = 1000)
	public String getFileExtension() {
		return this.fileExtension;
	}

	public void setFileExtension(String fileExtension) {
		this.fileExtension = fileExtension;
	}

	@Column(name = "mimeType", length = 1000)
	public String getMimeType() {
		return this.mimeType;
	}

	public void setMimeType(String mimeType) {
		this.mimeType = mimeType;
	}

	@Column(name = "fileSize")
	public Integer getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(Integer fileSize) {
		this.fileSize = fileSize;
	}

	@Column(name = "folder", length = 1000)
	public String getFolder() {
		return this.folder;
	}

	public void setFolder(String folder) {
		this.folder = folder;
	}

	@Column(name = "fileBatch", length = 1000)
	public String getFileBatch() {
		return this.fileBatch;
	}

	public void setFileBatch(String fileBatch) {
		this.fileBatch = fileBatch;
	}

	@Column(name = "iduser01")
	public Integer getIduser01() {
		return this.iduser01;
	}

	public void setIduser01(Integer iduser01) {
		this.iduser01 = iduser01;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date01", length = 19)
	public Date getDate01() {
		return this.date01;
	}

	public void setDate01(Date date01) {
		this.date01 = date01;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "media")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
