package com.g10.JolieWeb.Entity;
// default package
// Generated Dec 2, 2022, 3:53:02 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Review generated by hbm2java
 */
@Entity
@Table(name = "review", catalog = "jolie")
public class Review implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Accountinfo accountinfo;
	private Product product;
	private int rating;
	private String comment;
	private Integer image;
	private Date date01;

	public Review() {
	}

	public Review(Accountinfo accountinfo, Product product, int rating) {
		this.accountinfo = accountinfo;
		this.product = product;
		this.rating = rating;
	}

	public Review(Accountinfo accountinfo, Product product, int rating, String comment, Integer image, Date date01) {
		this.accountinfo = accountinfo;
		this.product = product;
		this.rating = rating;
		this.comment = comment;
		this.image = image;
		this.date01 = date01;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUser", nullable = false)
	public Accountinfo getAccountinfo() {
		return this.accountinfo;
	}

	public void setAccountinfo(Accountinfo accountinfo) {
		this.accountinfo = accountinfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProduct", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "rating", nullable = false)
	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	@Column(name = "comment", length = 500)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "image")
	public Integer getImage() {
		return this.image;
	}

	public void setImage(Integer image) {
		this.image = image;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date01", length = 19)
	public Date getDate01() {
		return this.date01;
	}

	public void setDate01(Date date01) {
		this.date01 = date01;
	}

}
